# .streamlit/secrets.toml
[uipath]
url          = "https://cloud.uipath.com/palanxivwkws"
tenant       = "DefaultTenant"
folder_id    = "946a9807-8e8d-4862-ba2d-1222480a0f97"
slug         = "myAutomationTrigger"
bearer_token = "rt_35E2F3E38F9DC2D363D615CBF0F90650B7F9C95F315071E941AEF50BC0760F90-1"
